name: WebGPU WASM build

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WebGPU crate
        run: |
          cd web-rust
          ./build.sh

      - name: Upload web bundle
        uses: actions/upload-artifact@v4
        with:
          name: web-rust-pkg
          path: |
            web-rust/index.html
            web-rust/README.md
            web-rust/pkg
